name: NuGet Build & Push to GitHub

inputs:
  pushBuild:
    required: false
    type: boolean
    default: false
  version:
    required: true
    type: string
  isRcBuild:
    required: false
    type: boolean
    default: false
  csprojPath:
    required: true
    type: string
  context:
    required: false
    type: string
    default: "."
  ghPAT:
    required: false
    type: string
    default: ""
  packageSourceId:
    required: false
    type: string
    defualt: "github"
    
runs:
  using: "composite"
  steps:    

    - name: Pack Stable
      if: ${{ !inputs.isRcBuild }}
      shell: bash
      run: dotnet pack ${{ inputs.context }}/${{ inputs.csprojPath }} -c Release -p:PackageVersion=${{ inputs.version }}
      
    - name: Pack RC
      if: ${{ inputs.isRcBuild }}
      shell: bash
      run: dotnet pack ${{ inputs.context }}/${{ inputs.csprojPath }} -c Release -p:PackageVersion=${{ inputs.version }}-rc

    - name: Publish to GitHub packages
      if: ${{ inputs.pushBuild }}
      shell: bash
      run: dotnet nuget push ${{ inputs.context }}/**/*.nupkg --api-key ${{ inputs.ghPAT }} --source "${{ inputs.packageSourceId }}"
