name: NuGet Build & Push to GitHub

inputs:
  pushBuild:
    required: true
    type: boolean
  version:
    required: true
    type: string
  isRcBuild:
    required: false
    type: boolean
    default: false
  csprojPath:
    required: true
    type: string
  context:
    required: true
    type: string
    default: "."
  ghPAT:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:    

    - name: Pack Stable
      if: ${{ !inputs.isRcBuild }}
      shell: bash
      run: dotnet pack ${{ inputs.context }}/${{ inputs.csprojPath }} -c Release -p:PackageVersion=${{ inputs.version }}
      
    - name: Pack RC
      if: ${{ inputs.isRcBuild }}
      shell: bash
      run: dotnet pack ${{ inputs.context }}/${{ inputs.csprojPath }} -c Release -p:PackageVersion=${{ inputs.version }}-rc
      
    - name: Prep packages
      if: ${{ inputs.pushBuild }}
      shell: bash
      run: dotnet nuget add source --username thenightangel17 --password ${{ inputs.ghPAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/mlx-development/index.json"
      
    - name: Publish to GitHub packages
      if: ${{ inputs.pushBuild }}
      shell: bash
      run: dotnet nuget push ${{ inputs.context }}/**/*.nupkg --api-key ${{ inputs.ghPAT }} --source "github"
