name: NuGet Build & Push to GitHub

inputs:
  pushBuild:
    required: false
    type: boolean
    default: false
  version:
    required: true
    type: string
  isRcBuild:
    required: false
    type: boolean
    default: false
  csprojPath:
    required: true
    type: string
  context:
    required: false
    type: string
    default: "."
  ghPAT:
    required: false
    type: string
    default: ""
  packageSourceId:
    required: false
    type: string
    defualt: "github"
    
runs:
  using: "composite"
  steps:    

    - name: Pack Stable
      shell: bash
      run: |
        if [[ ${{ !inputs.isRcBuild }} ]]; then
          dotnet pack ${{ inputs.context }}/${{ inputs.csprojPath }} -c Release -p:PackageVersion=${{ inputs.version }}
        fi
        exit 0
        
      
    - name: Pack RC
      shell: bash
      run: |
        if [[ ${{ inputs.isRcBuild }} ]]; then
          dotnet pack ${{ inputs.context }}/${{ inputs.csprojPath }} -c Release -p:PackageVersion=${{ inputs.version }}-rc
        fi 
        exit 0

    - name: Publish to GitHub packages
      shell: bash
      run: |
        if [[ ${{ !inputs.isRcBuild }} ]]; then
          dotnet nuget push ${{ inputs.context }}/**/*.nupkg --api-key ${{ inputs.ghPAT }} --source "${{ inputs.packageSourceId }}"
        fi
        exit 0
